### ISSUE TITLE
About resolution setting between DOE, Sensor and psf. 

### ISSUE THREAD

**Issue by BecIcan** [singer-yang/DeepLens#5]
Hi singer-yang,
First congratulate you on your amazing project. I have tried to reproduce your work and I was able to run the demo successfully. However, I have some questions about the resolution settings in DOE optimization:

1. Why the physical size of the DOE need to match the sensor's in deepens/diffraclens.py? Does it mean designed DOE' physical size cannot exceed the sensor's?
2. In rendering images with psf, psf kernel size is 101*101(default setting) which is smaller than sensor's resolution(default 1024). Can I understand that the sensor resolution is matched to the DOE just for better psf simulation? If I design a DOE with a 4cm aperture, and the simulation matches the sensor size to it, but in reality I don't have such a large sensor, will I be able to get experimental results that are consistent with the simulation?

Best regards.

**Comment by singer-yang** [comment]
Hello Beclcan,

Thanks a lot for your interest! 

> Why the physical size of the DOE need to match the sensor's in deepens/diffraclens.py?

No, of course you can use a different physical size. But you need to modify the current code for this.

> In rendering images with psf, psf kernel size is 101*101(default setting) which is smaller than sensor's resolution(default 1024).

We crop the field into a smaller resolution PSF because (1) the valid PSF is small, and (2) to reduce computing complexity.

> Can I understand that the sensor resolution is matched to the DOE just for better psf simulation?

We match the resolutions to make it easier to understand our algorithm. You can use different DOE and sensor resolutions and the results will not change.

> If I design a DOE with a 4cm aperture, and the simulation matches the sensor size to it, but in reality I don't have such a large sensor, will I be able to get experimental results that are consistent with the simulation?

The pixel size is the most important. You need to make sure the pixel size between simulation and real capture are the same.

Please feel free to ask if you are still unclear!

Best,
singer-yang

**Comment by BecIcan** [comment]
I am clear and thank you very much for your answer. Good luck！

**Comment by singer-yang** [comment]
Great! I will close this issue.
